Blog/__init__.py
from flask import Blueprint

blog = Blueprint(
    "blog",
    __name__,
    template_folder="templates/blog",
)

from . import views
from . import model


from .api import bp

blog.register_blueprint(bp, url_prefix="/api/")

Blog/api/__init__.py
from flask import Blueprint

bp = Blueprint("api", __name__)

from . import views

Blog/api/views.py
from flask import make_response

from . import bp

from Blog.model import Post
from Core.extensions import db


@bp.route("/latest/posts/", methods=["GET"])
def get_latest_blog_post():
    """this view return latest blog posts in json format
    uses in index slider
    """
    query = db.session.query(Post).order_by(Post.CreatedTime.desc()).limit(10)
    result = db.session.execute(query)
    return [each.to_dict() for each in result], 200

Blog/views.py
from flask import render_template, abort, request

from Core.extensions import db
from Admin.utils import get_admin
from Admin.model import Admin

from . import blog
from .model import Post


@blog.route("/", methods=["GET"])
def index_get():
    """blog main index return all post in  pagination mode
    and order by creation date"""
    page = request.args.get(key="page", default=1, type=int)
    query = db.select(Post).order_by(Post.CreatedTime.desc())

    query_result = db.paginate(select=query, per_page=16, page=page, error_out=True)

    ctx = {"posts": query_result, "current_page": page}
    return render_template("blog-list.html", ctx=ctx)


@blog.route("/author/<string:username>/", methods=["GET"])
def author_index_get(username: str) -> str:
    """author's special page for posts"""
    query = db.session.query(Admin).filter_by(Username=username)

    author = db.session.execute(query).scalar_one_or_none()
    if not author:
        abort(404)

    page = request.args.get(key="page", default=1, type=int)

    query = (
        db.session.query(Post)
        .filter_by(AuthorID=author.id)
        .order_by(Post.CreatedTime.desc())
    )
    query_result = db.paginate(select=query, per_page=16, page=page, error_out=True)

    ctx = {"author": author, "posts": query_result, "current_page": page}
    return render_template("author-post-list.html", ctx=ctx)


@blog.route("/s/<string:slug>/", methods=["GET"])
def show_post_by_slug_get(slug):
    """Showing posts base on slug in url"""
    query = db.session.query(Post).filter_by(Slug=slug)
    query_result = db.session.execute(query).scalars()
    query_result = db.session.execute(query).sca

    if (
        not query_result
    ):  # TODO: replace it with a custom template like blog post is not found, see similars
        abort(404)

    ctx = {"post": query_result, "author": get_admin(query_result.AuthorID)}

    return render_template("blog-details.html", ctx=ctx)


@blog.route("/<string:title>/", methods=["GET"])
def show_post_by_title_get(title):
    """Showing posts base on title in url"""
    title = title.replace("-", " ")
    query = db.session.query(Post).filter_by(Title=title)
    query_result = db.session.execute(query).scalar_one_or_none()

    if (
        not query_result
    ):  # TODO: replace it with a custom template like blog post is not found, see similars
        abort(404)

    ctx = {"post": query_result, "author": get_admin(query_result.AuthorID)}
    return render_template("blog-details.html", ctx=ctx)

Blog/templates/blog/author-post-list.html
{% extends 'base.html' %}

{% block title %}
    نوشته های {{ ctx.author.Username }}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block content %}
    {% include 'components/header.html' %}

    <div class="container-fluid">
        <section class="persian-font">
            <div class="row justify-content-center align-items-center my-5">
                <h2 class="text-center my-3">آخرین نوشته های <span class="text-primary text-decoration-underline">{{ ctx.author.Username }}</span></h2>
                <div class="col-12 col-md-10">
                    <div class="row">
                        {% for post in ctx.posts %}
                            <div class="col-11 col-sm-6 col-md-4 col-lg-3 my-3">
                            <div class="card shadow-md">
                                <a href="{{ url_for('blog.show_post_by_slug_get', slug=post.Slug) }}">
        {#                            <img src="{{ 'blog/media/'+post.get_image_at(0) | StorageUrl }}" alt="Image cant be loaded" class="card-img-top inset h-100 w-100">#}
                                    <img src="https://eeeico.com/wp-content/uploads/2020/04/Capacitor.jpg" alt="Image cant be loaded" class="card-img-top inset h-100 w-100">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title text-center">{{ post.Title}}</h5>
                                    <p class="overflow-hidden text-justify" style="max-height: 100px">
                                        {{ post.ShortIntro | safe }}
                                    </p>
                                    <div class="t-time-info my-2 text-muted d-flex justify-content-between align-items-center flex-wrap fs-0-8">
                                        <span>
                                            <i class="bi bi-calendar"></i>
                                            {{ post.ConvertToJalali(post.CreatedTime) }} |
                                        </span>
                                        <span>
                                            <i class="bi bi-clock"></i>
                                            زمان مطالعه:
                                            {{ post.ReadingTime }}
                                            دقیقه
                                        </span>
                                    </div>
                                    <div class=" d-flex justify-content-center align-items-center w-100">
                                        <a href="{{ url_for('blog.show_post_by_title_get', title=post.make_url()) }}" class="btn btn-primary col-12 rounded-3 text-white">خواندن</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>


           <nav dir="rtl"  class="d-flex justify-content-center align-items-center" aria-label="Page navigation" dir="ltr">
                <ul class="pagination">
                        {% if ctx.posts.pages - ctx.current_page  >= 0 and ctx.current_page != 1 %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{{ url_for('blog.author_index_get', page=ctx.current_page - 1, username=ctx.author.Username) }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page in ctx.posts.iter_pages(right_edge=1, left_edge=1,right_current=1, left_current=1) %}
                            {% if page %}
                                {% if page == ctx.current_page %}
                                    <li class="page-item">
                                        <a class="page-link active"
                                           href="{{ url_for('blog.author_index_get', page=ctx.current_page, username=ctx.author.Username) }}">{{ page }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ url_for('blog.author_index_get', page=page, username=ctx.author.Username) }}">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}

                        {% if ctx.posts.pages - ctx.current_page > 0 %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{{ url_for('blog.author_index_get', page=ctx.current_page + 1, username=ctx.author.Username) }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
           </nav>



            </div>
        </section>
    </div>



    {% include 'components/footer.html' %}
    {% include 'components/mobile-navbar.html' %}
{% endblock content %}


{% block script %}
{% endblock script %}

Blog/templates/blog/blog-details.html
{% extends 'base.html' %}

{% block title %}
    {{ ctx.post.Title }} | {{ _('وبلاگ') }}
{% endblock title %}

{% block style %}
    {% include 'utils/owl-carousel.html' %}
{% endblock style %}
{% block content %}
    {% include 'components/header.html' %}


    <div class="container-fluid bg-gray">
        <section class="persian-font">
            <div class="row justify-content-center align-items-center py-2">

                    <div class="card col-sm-10 col-md-8 col-11 p-0">
                        <!--header -->
                        <div class="card-header">
                            <h1 class="post-title" style="">{{ ctx.post.Title }}</h1>
                            <nav style="--bs-breadcrumb-divider: '>';" class="fs-0-8"  aria-label="breadcrumb">
                              <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a class="text-decoration-none text-muted" href="{{ url_for('web.index_get') }}">صفحه اصلی</a></li>
                                <li class="breadcrumb-item"><a class="text-decoration-none text-muted" href="{{ url_for('blog.index_get') }}">بلاگ</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{ ctx.post.Title }}</li>
                              </ol>
                            </nav>

                            <div class="author-info d-flex justify-content-between align-items-center flex-wrap">
                            <div>
                                <span class="text-muted fs-0-8" >نوسته شده توسط</span>
                                <a class="text-decoration-none text-primary" href="{{ url_for('blog.author_index_get', username=ctx.author.Username) }}">
                                    <i class="bi bi-person-circle"></i>
                                    <span>{{ ctx.author.Username }}</span>
                                </a>
                            </div>
                            <div class="t-time-info">
                                <span class="text-muted fs-0-8" dir="rtl">
                                    <i class="bi bi-calendar"></i>
                                    {{ ctx.post.ConvertToJalali(ctx.post.CreatedTime) }} |
                                    <i class="bi bi-clock"></i>
                                    زمان مطالعه:
                                    {{ ctx.post.ReadingTime }}
                                    دقیقه
                                </span>
                            </div>
                        </div>
                        </div>
                        <!--body -->
                        <div class="card-body">
                            <div class="post-content my-3" style="text-align: justify">
                                <div class=lh-lg">{{ ctx.post.Content | safe }}</div>
                                   <div class="post-tags">
                                    {% for each in ctx.post.get_tags() %}
                                        <a href="#category" class="cursor-pointer text-decoration-none my-2 badge rounded bg-secondary text-white fs-0-8">#{{ each }}</a>
                                    {% endfor %}
                                   </div>
                            </div>
                        </div>
                        <!--footer -->
                        <div class="card-footer">
                            <div class="share-btns ">
                            <p class="my-2">اشتراک گذاری در</p>
                            <a target="_blank" href="https://telegram.me/share/url?url={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}" class="btn text-white my-2" style="background-color: #0088cc">
                                Telegram
                                <i class="bi bi-telegram"></i>
                            </a>
                            <a target="_blank" href="https://facebook.com/sharer/sharer.php?u={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}" class="btn text-white my-2" style="background-color: #3b5998">
                                facebook
                                <i class="bi bi-facebook"></i>
                            </a>
                            <a target="_blank" href="https://twitter.com/intent/tweet/?text={{ ctx.post.ShortIntro }}&url={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}" class="btn btn-primary text-white my-2"  style="background-color: #1DA1F2">
                                twitter
                                <i class="bi bi-twitter"></i>
                            </a>
                            <a target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}&title={{ ctx.post.Title }}&summary={{ ctx.post.ShortIntro }}&source={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}" class="btn text-white my-2" style="background-color: #0077b5">
                                linkedin
                                <i class="bi bi-linkedin"></i>
                            </a>
                            <a target="_blank" href="https://reddit.com/submit/?url={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}&resubmit=true&title={{ ctx.post.Title }}" class="btn text-white my-2" style="background-color: #FF5700">
                                reddit
                                <i class="bi bi-reddit"></i>
                            </a>
                            <a target="_blank" href="mailto:?subject={{ ctx.post.Title }}&body={{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}"
                               class="btn text-white bg-secondary my-2" >
                                E-mail
                                <i class="bi bi-envelope"></i>
                            </a>
                            <div class="short-link my-2"  dir="ltr">
                                <span onclick="Copy2clipboard(`{{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}`);" class="border border-dark rounded-5 p-2 cursor-pointer"><i class="bi bi-clipboard mx-2 text-dark"></i><span >{{ url_for('blog.show_post_by_slug_get', slug=ctx.post.Slug, _external=True) }}</span></span>
                            </div>
                        </div>
                        </div>
                    </div>

                    <!-- related posts -->
                    <div class="col-md-8 col-11 my-5">
                        <h3 class="my-4">{{ _('سایر نوشته ها') }}</h3>
                        <div class="owl-carousel owl-theme owl-carousel-blog-post-slider position-relative">
                            {% for i in range(5) %}
                                <div class="item">
                                    <div class="card text-center shadow-md">
                                        <a href=""><img src="https://eeeico.com/wp-content/uploads/2020/04/Capacitor.jpg" alt="website template image" class="card-img-top inset h-100 w-100"></a>
                                        <div class="card-body">
                                            <h5 class="card-title text-brand text-start" dir="rtl">API چیست؟
                                            </h5>
                                            <p class="text-secondary overflow-hidden" style="max-height: 100px;" dir="rtl">
                                                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است
                                            </p>
                                            <div class="d-flex justify-content-between align-items-center my-1">
                                                <p class="fs-7 text-secondary m-0">زمان مطالعه : <span class="text-primary fw-bold">5 دقیقه</span></p>
                                            </div>
                                            <div class=" d-flex justify-content-center align-items-center w-100">
                                                <a href="#" class="btn btn-primary col-12 rounded-3 text-white">خواندن</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

            </div>
        </section>
    </div>



    {% include 'components/footer.html' %}
    {% include 'components/mobile-navbar.html' %}
{% endblock content %}


{% block script %}
    <script src="{{ 'blog/js/blog-details.js' | StorageUrl }}"></script>
{% endblock script %}

Blog/templates/blog/blog-list.html
{% extends 'base.html' %}

{% block title %}
    آخرین مطالب وبلاگ
{% endblock title %}

{% block style %}
{% endblock style %}
{% block content %}
    {% include 'components/header.html' %}


    <div class="container-fluid">
        <section class="persian-font">
            <div class="row justify-content-center align-items-center my-5">
                <h2 class="text-center my-3">آخرین نوشته های وبلاگ</h2>
                <div class="col-12 col-md-10">
                    <div class="row">
                        {% if ctx.posts.pages %}
                            {% for post in ctx.posts %}
                                <div class="col-11 col-sm-6 col-md-4 col-lg-3 my-3">
                                    <div class="card shadow-md">
                                    <a href="{{ url_for('blog.show_post_by_slug_get', slug=post.Slug) }}">
            {#                            <img src="{{ 'blog/media/'+post.get_image_at(0) | StorageUrl }}" alt="Image cant be loaded" class="card-img-top inset h-100 w-100">#}
                                        <img src="https://eeeico.com/wp-content/uploads/2020/04/Capacitor.jpg" alt="Image cant be loaded" class="card-img-top inset h-100 w-100">
                                    </a>
                                    <div class="card-body">
                                        <h5 class="card-title text-center">{{ post.Title}}</h5>
                                        <p class="overflow-hidden text-justify" style="max-height: 100px">
                                            {{ post.ShortIntro | safe }}
                                        </p>
                                        <div class="t-time-info my-2 text-muted d-flex justify-content-between align-items-center flex-wrap fs-0-8">
                                            <span>
                                                <i class="bi bi-calendar"></i>
                                                {{ post.ConvertToJalali(post.CreatedTime) }} |
                                            </span>
                                            <span>
                                                <i class="bi bi-clock"></i>
                                                زمان مطالعه:
                                                {{ post.ReadingTime }}
                                                دقیقه
                                            </span>
                                        </div>
                                        <div class=" d-flex justify-content-center align-items-center w-100">
                                            <a href="{{ url_for('blog.show_post_by_title_get', title=post.make_url()) }}" class="btn btn-primary col-12 rounded-3 text-white">خواندن</a>
                                        </div>
                                    </div>
                                </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-11 my-3">
                                <h3 class="text-center text-muted my-3">مطلبی یافت نشد</h3>
                            </div>
                        {% endif %}
                    </div>
                </div>

            <nav dir="rtl" class="d-flex justify-content-center align-items-center" aria-label="Page navigation" dir="ltr">
                <ul class="pagination">
                        {% if ctx.posts.pages - ctx.current_page  >= 0 and ctx.current_page != 1 %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{{ url_for('blog.index_get', page=ctx.current_page - 1) }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page in ctx.posts.iter_pages(right_edge=1, left_edge=1,right_current=1, left_current=1) %}
                            {% if page %}
                                {% if page == ctx.current_page %}
                                    <li class="page-item">
                                        <a class="page-link active"
                                           href="{{ url_for('blog.index_get', page=ctx.current_page) }}">{{ page }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="{{ url_for('blog.index_get', page=page) }}">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}

                        {% if ctx.posts.pages - ctx.current_page > 0 %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{{ url_for('blog.index_get', page=ctx.current_page + 1) }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
           </nav>


            </div>
        </section>
    </div>



    {% include 'components/footer.html' %}
    {% include 'components/mobile-navbar.html' %}
{% endblock content %}


{% block script %}
{% endblock script %}

Blog/templates/blog/tag-list.html
{% extends 'base.html' %}

{% block title %}
پست های مربوط به {{ ctx.tag.Name }}
{% endblock title %}

{% block style %}
{% endblock style %}
{% block content %}
    {% include 'components/header.html' %}


    <div class="container-fluid">
        <section class="persian-font">
            <div class="row justify-content-center align-items-center my-5">
                <h2 class="text-center my-3">پست های مربوط به<span class="text-primary text-decoration-underline">{{ ctx.tag.Name }}</span></h2>
                <div class="col-12 col-md-10">
                    <div class="row">
                        {% for post in ctx.posts %}
                            <div class="col-11 col-sm-6 col-md-4 col-lg-3 my-3">
                            <div class="card shadow-md">
                                <a href="{{ url_for('blog.show_post_by_slug_get', slug=post.Slug) }}">
        {#                            <img src="{{ 'blog/media/'+post.get_image_at(0) | StorageUrl }}" alt="Image cant be loaded" class="card-img-top inset h-100 w-100">#}
                                    <img src="https://eeeico.com/wp-content/uploads/2020/04/Capacitor.jpg" alt="Image cant be loaded" class="card-img-top inset h-100 w-100">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title text-center">{{ post.Title}}</h5>
                                    <p class="overflow-hidden text-justify" style="max-height: 100px">
                                        {{ post.ShortIntro | safe }}
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center my-1">
                                        <p class="fs-7 text-secondary m-0">زمان مطالعه : <span class="text-primary fw-bold">{{ post.ReadingTime }} دقیقه</span></p>
                                    </div>
                                    <div class=" d-flex justify-content-center align-items-center w-100">
                                        <a href="{{ url_for('blog.show_post_by_title_get', title=post.make_url()) }}" class="btn btn-primary col-12 rounded-3 text-white">خواندن</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>



    {% include 'components/footer.html' %}
    {% include 'components/mobile-navbar.html' %}
{% endblock content %}


{% block script %}
{% endblock script %}